-- MySQL Script generated by MySQL Workbench
-- Mon Jul 20 23:50:54 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema catesys
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema catesys
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `catesys` DEFAULT CHARACTER SET utf8 ;
USE `catesys` ;

-- -----------------------------------------------------
-- Table `catesys`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catesys`.`aluno` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NULL,
  `nome_responsavel` VARCHAR(100) NULL,
  `telefone_responsavel` VARCHAR(11) NULL,
  `data_nascimento` DATE NULL,
  `status` INT NULL COMMENT '1 - ativo\n0 -  inativo',
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catesys`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catesys`.`professor` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NULL,
  `senha` VARCHAR(20) NULL,
  `status` INT NULL COMMENT '1 - ativo\n0 - inativo\n',
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catesys`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catesys`.`turma` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `status` INT NULL COMMENT '1 - ativo\n0 - inativo',
  `professor_matricula` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_turma_professor_idx` (`professor_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_turma_professor`
    FOREIGN KEY (`professor_matricula`)
    REFERENCES `catesys`.`professor` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catesys`.`aula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catesys`.`aula` (
  `codigo` INT NOT NULL,
  `data` DATE NOT NULL,
  `turma_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_aula_turma1_idx` (`turma_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_aula_turma1`
    FOREIGN KEY (`turma_codigo`)
    REFERENCES `catesys`.`turma` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catesys`.`turma_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catesys`.`turma_aluno` (
  `turma_codigo` INT NOT NULL,
  `aluno_matricula` INT NOT NULL,
  PRIMARY KEY (`turma_codigo`, `aluno_matricula`),
  INDEX `fk_turma_has_aluno_aluno1_idx` (`aluno_matricula` ASC) VISIBLE,
  INDEX `fk_turma_has_aluno_turma1_idx` (`turma_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_turma_has_aluno_turma1`
    FOREIGN KEY (`turma_codigo`)
    REFERENCES `catesys`.`turma` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_has_aluno_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `catesys`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `catesys`.`presenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `catesys`.`presenca` (
  `aula_codigo` INT NOT NULL,
  `aluno_matricula` INT NOT NULL,
  `presente` INT NULL COMMENT '0 - faltou \n1 - presente',
  PRIMARY KEY (`aula_codigo`, `aluno_matricula`),
  INDEX `fk_aula_has_aluno_aluno1_idx` (`aluno_matricula` ASC) VISIBLE,
  INDEX `fk_aula_has_aluno_aula1_idx` (`aula_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_aula_has_aluno_aula1`
    FOREIGN KEY (`aula_codigo`)
    REFERENCES `catesys`.`aula` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aula_has_aluno_aluno1`
    FOREIGN KEY (`aluno_matricula`)
    REFERENCES `catesys`.`aluno` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
